const RoutPath = {
    RootRoute: "/",
    Cart: "/cart",
    ChangePassword: "/change-password",
    Checkout: "/checkout",
    ProfileDashboard: "/profile-dashboard",
    SpecialOffer: "/profile-dashboard/specialoffer",
    PaymentPage: "/paymentPage",
    Thankyou: "/thank-you",
    MyOrders: "/my-orders",
    SupportTicket: "/support-ticket",
    Logout: "/logout",
    Login: "/login",
    MyAccount: "/my-account",
    MyProfile: "/customer-profile",
    Plan: "/plan",
    Product: "/product",
    Profile: "/profile",
    Register: "/register",
    TopUpPayment: "/topUp-payment",
    BillingDetails: "/billing-details",
    CartSummary: "/cart-summary",
    AddonList: "/profile-dashboard/addonlist",
    PayBill: "/pay-bill",
    DepositAddons: "/profile-dashboard/deposit-addons",
    FriendsAndFamilyList: "/profile-dashboard/friends-family-list",
    ProfilePayment: "/profile-payment/stl-pay",
    searchResult: "/search-results",
    AddTicket: "/add-ticket",
    ManageFnF: "/manage-friends-and-family",
    FriendsAndFamily: "/profile-dashboard/friends-and-family",
    ChangePlan: "/change-plan",
    TermCondtion: "/term-condition",
    CommunicationPreference: "/communication-preference",
    PrepaidBalance: "/prepaid-balance",
    GftingAddon: "/profile-dashboard/gifting-addon",
    MySubscriptions: "/my-subscriptions",
};

export default RoutPath;
